services:
  - type: web
    name: draw4friends-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /  # Optional: Reiner WebSocket-Server empfiehlt Option A (HTTP-Server + WS)
  - type: web
    name: draw4friends-frontend
    runtime: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist